
CREATE TABLE IF NOT EXISTS accounts (
  id bigint generated by default as identity not null,
  username text not null,
  password text null,
  token text null,
  balance smallint null,
  constraint accounts_pkey primary key (id)
) TABLESPACE pg_default;

-- Create transaction_log table
CREATE TABLE IF NOT EXISTS transaction_log (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount DECIMAL(20, 2) NOT NULL,
    type VARCHAR(20) CHECK (type IN ('deposit', 'withdraw')),
    balance_after DECIMAL(20, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create poker_log table
CREATE TABLE IF NOT EXISTS poker_log (
    id SERIAL PRIMARY KEY,
    data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create game_log table
CREATE TABLE IF NOT EXISTS game_log (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount DECIMAL(20, 2) NOT NULL,
    type VARCHAR(20) CHECK (type IN ('lose', 'win')),
    balance_after DECIMAL(20, 2),
    poker_log_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
